"""
services/llm_service.py — LLM answer generation using Gemini
"""
import logging
import google.generativeai as genai
from config import get_settings

logger = logging.getLogger(__name__)

def generate_answer(query: str, context: str) -> str:
    """
    Generate an LLM answer from a query and retrieved context.
    
    Args:
        query:   The user's medical symptoms/question.
        context: The text of the retrieved medical records.

    Returns:
        The text explanation generated by the LLM.
    """
    settings = get_settings()
    
    if not settings.gemini_api_key:
        logger.error("GEMINI_API_KEY is missing from environment variables.")
        raise ValueError("Gemini API key is missing.")

    # Configure the Gemini client
    genai.configure(api_key=settings.gemini_api_key)
    
    # Use the configured model or default flash model
    model_name = getattr(settings, "gemini_model", "gemini-2.5-flash")
    
    prompt = f"""You are a healthcare assistant.

Context:
{context}

User symptoms:
{query}

Explain possible medical conditions clearly.

Return only the explanation.
"""

    logger.info("Calling Gemini model: %s", model_name)
    
    try:
        model = genai.GenerativeModel(model_name)
        
        # Configure generation config for temperature
        generation_config = genai.types.GenerationConfig(
            temperature=0.2,
        )
        
        response = model.generate_content(
            prompt,
            generation_config=generation_config
        )
        
        return response.text.strip()
    except Exception as exc:
        logger.error("Gemini call failed: %s", exc)
        raise RuntimeError(f"LLM Generation failed: {exc}") from exc